[params]
    author = "Christian Mahnke"
    homeTitle = "Projektemacher"
    description = "Blog Potpourri"
    keywords = "blog, book, digitization, history, cultural history"
    info = "Blogfabrik"
    logoUrl1 = "/images/laborant.svg"
    logoUrl2 = "/images/laborant.svg"
    logoLink = "logo/"
    footercontent = ""
    copyrightYears = "2009 - 2026"

    hideFooter = true
    hideCredits = true
    hideCopyright = true
    since = 2020
    news = 10

    colorscheme = "light"

    favicon_16 = "/images/favicon-16.png"
    favicon_32 = "/images/favicon-32.png"
    favicon_svg = "/images/cm.svg"
    #stylesheets = []
    #stylesheets = ["https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Lora:wght@400;700&family=Source+Code+Pro:wght@400;700&display=swap"]
    disableScale = true
    wikidata = false
    debug = true

    [params.footer]
        privacy = true

    [params.style]
      # Colors
      bg-color = '#FAFAFA'
      fg-color = '#212121'
      alt-bg-color = '#E0E0E0'
      alt-fg-color = '#000'
      link-color = '#1565c0'
      # Colors dark
      bg-color-dark = '#212121'
      fg-color-dark = '#dadada'
      alt-bg-color-dark = '#424242'
      alt-fg-color-dark = '#dadada'
      link-color-dark = '#42a5f5'
      nav-color = '#293133'
